### ISSUE TITLE
Embedding graphs in R pres. // Error: object 'vI' not found (Mac OS X 10.9.5 - RStudio 0.99.893)

### ISSUE THREAD

**Issue by Camila-RV** [HertieDataScience/SyllabusAndLectures#116]
I would like to embed graphs in R presentation. 
I'm having the following Error message:

"Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  object 'vI' not found
In addition: Warning message:
package ‘plm’ was built under R version 3.2.3 
Error: package or namespace load failed for ‘plm’"

Do you have any idea know how I should proceed on the:
1. error related to object 'vI'?
2. the second issue I tried to solve it the same way I did with another package:
   2.1. I downloaded a older version in CRAN
   2.2  In Terminal, I copied the unziped folder from my Desktop into the R library:
          cp -R ~/Desktop/plm /Library/Frameworks/R.framework/Versions/3.2/Resources/library
          However, this time I couldn't solve it that way.

I appreciate any comments you may have about it.

Best, 

Camila

**Comment by christophergandrud** [comment]
I believe we solved this in office hours. It had something to do with a corrupted library where. We created a new one (via updating R) and reinstalled the package.
