### ISSUE TITLE
How to delete documents/datasets from the repository

### ISSUE THREAD

**Issue by jasmincantzler** [HertieDataScience/SyllabusAndLectures#39]
Dear all,

I accidentally uploaded an R.Data file, which I would like to delete from the repository. Does anyone know how to get rid of this aka how to delete files from the repository?
(we have a similar problem with a csv. file)

Any help is much appreciated!
Cheers,
Jasmin

**Comment by bctclc** [comment]
You can delete it online. Just click the trash can bottom, if this is what
you mean.

[image: Inline image 1]

On Fri, Oct 2, 2015 at 11:09 AM, jasmincantzler <notifications@github.com>
wrote:

> Dear all,
>
> I accidentally uploaded an R.Data file, which I would like to delete from
> the repository. Does anyone know how to get rid of this aka how to delete
> files from the repository?
> (we have a similar problem with a csv. file)
>
> Any help is much appreciated!
> Cheers,
> Jasmin
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/HertieDataScience/SyllabusAndLectures/issues/39>.
>



-- 
刘畅 Chang LIU
Claire LIU
+49 162 5236352

乔治城大学McCourt公共政策学院公共政策专业
Master of Public Policy, McCourt School of Public Policy, Georgetown
University

With head and heart.

**Comment by jasmincantzler** [comment]
There is no delete button, which is why I ask

![screenshot 2015-10-02 11 12 46](https://cloud.githubusercontent.com/assets/14014018/10243112/8dd5d6a2-68f6-11e5-88e5-c364bccb0b8e.png)

**Comment by bjoernboening** [comment]
Hi Jasmin,
yesterday I had the same issue and I found out you can manage it on your machine in your files as well. You should have a binder for your repository files on your machine. find and delete it there and sync with git. is that what you needed?

**Comment by LisaKatharina** [comment]
I think deleting it directly in your Explorer makes sense. The folder should be somewhere like "C:\Users\Username\Documents\GitHub" but depends on how you set it up. Do not forget to sync with the GitHub desktop app afterwards, though. Hope that helps.

**Comment by christophergandrud** [comment]
Thanks everyone for contributing. Yep, deleting it locally on your machine and then committing/syncing will remove it from GitHub as well.

A good idea in the future is to include `*.RData` in your *.gitignore* file. This will prevent git from tracking new .RData files. 

Another good idea is to go into your RStudio preferences and have it `Never` save your workspace as an .RData file. Not only does this prevent you from creating extraneous files to begin with, it also is better for reproducibility as your code won't accidentally depend on a locally saved workspace.

![never_rdata](https://cloud.githubusercontent.com/assets/1285805/10246233/38edbed2-6907-11e5-953c-30025d497343.png)
