### ISSUE TITLE
organization of work when using school computer in order to use stata

### ISSUE THREAD

**Issue by valerianie** [HertieDataScience/SyllabusAndLectures#40]
I had major issues today trying to organize a project which I mainly work on from my computer but for some bits I unfortunately need Stata, for which I need to use the school computers (no github!). 

the way i did it certainly messed things up (the file paths and also the location of files of interim results - since there is many different things going on and codes that have to be run and i cant just have an original dataset and a nice clean code i have to store those interim results). is there anything someone can recommend for organization of files when having to move computers? do i need full synchronisation?

**Comment by mcallaghan** [comment]
Dear valerianie,

I also have to use school computers, windows and stata for some things, which is very horrible. I managed to install github on them though... One way of doing it it ended up asking for an admin password, but, I think it was [here](https://desktop.github.com/) that I managed to do it and install it on my personal space on the computer, but this means you have to do it on every computer or only ever sit in one place.

**Comment by valerianie** [comment]
Dear mcallaghan,

Thanks! And yes, very horrible! Do you happen to remember on which computer you installed github using admin rights?

**Comment by mcallaghan** [comment]
Using that link I didn't need admin rights. It was the computer next to the window on the 3rd row, and the computer one away from the window in the 4th row, but I think it will just be on my space on that computer, you'll probably have to do it again...

**Comment by christophergandrud** [comment]
I haven't really worked on the School's computers for awhile, but last time I worked with them I did something similar to @mcallaghan.

Also, the first two rows of computers in our classroom should have git installed on them.
