### ISSUE TITLE
example of successful further working with dataset that someone else imported?

### ISSUE THREAD

**Issue by valerianie** [HertieDataScience/SyllabusAndLectures#41]
has anyone -  in a shared repository - successfully run someone elses code (in r) which imported some dataset which this someone also uploaded? 

i had problems with this before even when i had the entire repository synchronized and just wanted to see if someone else managed to do such a thing. shouldn't be that difficult?

**Comment by valerianie** [comment]
i found myself: https://github.com/HertieDataScience/Examples. thanks anyways!

**Comment by christophergandrud** [comment]
Could you provide a link to the repository? There may be some issue in the file paths.

**Comment by valerianie** [comment]
sorry for the late reply. i think that was the problem and its sorted out now.

**Comment by christophergandrud** [comment]
:+1:
