### ISSUE TITLE
Anyone have any long urls?

### ISSUE THREAD

**Issue by mcallaghan** [HertieDataScience/SyllabusAndLectures#50]
Sorry for another question, but I have some urls referenced using '@online'. They behave a bit strangely.

Firstly, I set the urldate to {YYYY-MM-DD} - I want them to say Author. Title. Date Accessed: Day month year, instead they say Author. Year. Title. Date Accessed: Day Month. I think that's a little confusing but maybe it is default behaviour a reason.

More seriously, I have one particularly long url, which doesn't line break and instead goes into the margins. I have googled the problem and only receive latex only solutions. I can't see any that relate to rmarkdown. Trouble is I'm not sure where to put the latex fix.. I've tried altering my default.tex file, but that doesn't seem to sort it. I've also tried just putting a space in the url, but then of  course it is a broken link :(.

Anyone encountered either problem? Is this detail too fine to worry about right now?

Thanks!

**Comment by mcallaghan** [comment]
It doesn't matter anymore - I used https://perma.cc/ to shorten it, which apparently is good scholarly practice anyway. I will ignore the other thing.

**Comment by christophergandrud** [comment]
Perma is good, though the links only last for two years unless you belong to a participating institution (I've tried to get Hertie involved, but they haven't). Given that Perma links aren't permanent for Hertie staff also check out: http://tex.stackexchange.com/questions/134191/line-breaks-of-long-urls-in-bibliography
