### ISSUE TITLE
Bibliography in PDF Output suddently missing

### ISSUE THREAD

**Issue by KatrinHeger** [HertieDataScience/SyllabusAndLectures#51]
Hi everyone,

so Benedikt and I were making changes to our Markdown file and when we generated the final pdf, the references were suddenly not shown in the pdf output file anymore (in contrast to the outputs before). We didn't change anything in the YAML field and the last line of the code (# References), where the bibliography is supposed to show. Does anyone have an idea what the issue might be? Thanks a lot!

**Comment by christophergandrud** [comment]
Could you send a URL to the code?

**Comment by christophergandrud** [comment]
I think I found your problem: you didn't include the BibTeX keys for each reference. I've added one example in a pull request: https://github.com/KatrinHeger/CollaborativeResearchProject/pull/1

Please do throughout and then your full bibliography will appear.

**Comment by mr-r0b0t** [comment]
Thank you for your advice! We fixed it and will send you the corrected version.
