### ISSUE TITLE
no offical markdown support for footnotes?

### ISSUE THREAD

**Issue by valerianie** [HertieDataScience/SyllabusAndLectures#54]
i am trying to include dynamic footnotes into a paper i a writing in markdown, and cannot find the solution. is it true that there is no official markdown support for footnotes? that would really surprise me.

**Comment by christophergandrud** [comment]
You certainly can use footnotes in R Markdown. See http://rmarkdown.rstudio.com/authoring_pandoc_markdown.html#footnotes.
