### ISSUE TITLE
Integer column positions error

### ISSUE THREAD

**Issue by natalia-alvarado** [HertieDataScience/SyllabusAndLectures#57]
Dear all,

When using the package "tidyr" and the fuction "gather" we ran into this error:

Error: All select() inputs must resolve to integer column positions.
The following do not:
*  "NumSrc"
*  "Rank"
*  "Lower"
*  "Upper"

These are the names of the variables that are in the columns.

We are not quite sure on how to resolve this issue. Any ideas?

Thank you in advance,

Natalia & Gabriel

**Comment by christophergandrud** [comment]
Hi, would it be possible to provide a link to the code so that we can reproduce the issue?

**Comment by natalia-alvarado** [comment]
Thank you for replying so fast.

It was our mistake, because first the columns were not properly named and also in the gather code we were using quotation marks when it didn't need them, once we got rid off them it worked.

**Comment by christophergandrud** [comment]
Perfect. Closing this issue.
