### ISSUE TITLE
Questions on grouped bar plot using ggplot2 (windows R.3.2.2)

### ISSUE THREAD

**Issue by bctclc** [HertieDataScience/SyllabusAndLectures#77]
Hi everyone!

I tried to plot grouped bar char using ggplot2 and this is my code:

```{r cho=F, warning=F, message=F, error=F, results='asis'}
ggplot(as.data.frame(meanagetable), aes(factor(POfactor), agemean, fill = Agegroupl)) + 
        geom_bar(stat="identity", position = "dodge") +
        scale_fill_manual(labels=c("young people", "middle-age people", "elder people"), 
                            values=c("dodgerblue", "blue", "dodgerblue4")) +
        scale_x_discrete(limits=c("recharge", "battery", "cost", "knowledge", "spec", 
                                  "choice","technology", "safety", "resale")) +
        xlab("Factors putting off buying EVs") +
        ylab("% of respondents") +
        labs(fill="  ") +
        theme(panel.grid =element_blank())
```

It worked out ok, but I want to make two changes, but I'm sure what to do.
1) make the y axis tidier by imposing the interval of 0.1
2) unorder the three bars within each group.

![rplot](https://cloud.githubusercontent.com/assets/13082566/11452176/3cd40ef2-95df-11e5-95f7-a72cc9b04608.png)

Thank you!

**Comment by christophergandrud** [comment]
It looks like your y-axis variable may be entered as a factor. Try making sure it is numeric. Also, you can `round` the variable before plotting. Another thing to try would be to use the ggplot2 `scale_y_continuous` function which allows you to specify breaks and tick labels.

Regarding the second one, perhaps try to turn the grouping variable into a factor with levels in order that you want the bars to be.

**Comment by bctclc** [comment]
Both worked out. Thank you very much!

**Comment by christophergandrud** [comment]
Great!
