### ISSUE TITLE
microsoft accounts

### ISSUE THREAD

**Issue by valerianie** [HertieDataScience/SyllabusAndLectures#82]
does somebody have a microsoft account (@hotmail or similar) that we could use for our data gathering? you don't have to give us the login but could sign up for a translation API and give us a key. that would be very helpful!

we need 2 or 3 of them...

max&valerie

**Comment by mcallaghan** [comment]
OK, we've created enough bogus accounts now... (but had to give lots of phone numbers to microsoft :fearful:)
