### ISSUE TITLE
Two-column layout presentation?

### ISSUE THREAD

**Issue by magaranoriko** [HertieDataScience/SyllabusAndLectures#83]
In our presentation, we'd like to show some texts on the left and a picture on a right in one page.
I used `<div class="columns-2">` and `</div>` as explained in [this page](http://rmarkdown.rstudio.com/ioslides_presentation_format.html)

When I knit the Rmd, R studio shows them correctly like this:
<img width="796" alt="slide1" src="https://cloud.githubusercontent.com/assets/14129966/11560229/530eb486-99bf-11e5-9286-a11d6be81886.png">

But once I open the html file in a browser (which I think is what we're going to do in class tomorrow), the two columns just collapse into one :(
<img width="1280" alt="slide2" src="https://cloud.githubusercontent.com/assets/14129966/11560265/96e474ca-99bf-11e5-8b17-02faa2e07805.png">

Does anyone know how to fix this? Just in case, the Rmd is [here](https://github.com/bctclc/Collaborative-Data-Analysis-Assignment2/blob/master/Final_Paper/Final_Presentation.Rmd).
Many thanks!

**Comment by christophergandrud** [comment]
Curious. 

Side notes: 

- if you want to run the presentation off of your own laptop, that's ok

- it would be good to remove the y and x axis labels and tick marks (I think there is an example in the recent lecture slides)

- I am unclear how the plot (which really shows regional variation) is a good representation of the information in the bullet point (which is about a national average). I personally would just show the map and say that on average 18% of British people are interested in EVs, with support being about 7% more in souther regions. Or something like that.

**Comment by magaranoriko** [comment]
Thank you so much for the quick answers!

Yeah, for this page I could just show the map. But I have another page with this 2 column layout (with more information). Maybe I'll bring my laptop tomorrow.

And thanks for the advice on plot labels!
