### ISSUE TITLE
Assignment 3 Due Date Extension due to WIFI issue

### ISSUE THREAD

**Issue by christophergandrud** [HertieDataScience/SyllabusAndLectures#99]
Due to the Hertie WIFI problem with accessing githhub.com, the due date for **Assignment 3 **has been moved to **Tuesday 19 April** (2016).

**Comment by mcallaghan** [comment]
Think I missed earlier discussion but I'm also having an issue accessing Github from my laptop at school. Do you know what the problem is?

**Comment by christophergandrud** [comment]
It has to do with the new network set up. It should be working now though.
